version: '3.0'
services:
  db:
    build: ./database
    ports:
      - "3307:3306"
  server:
    working_dir: /app
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
    volumes:
      - ./:/app
